#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>

#define AUDIO_INPUT_SAMPLE_RATE  16000
#define AUDIO_OUTPUT_SAMPLE_RATE 24000

// 如果使用 Duplex I2S 模式，请注释下面一行
#define AUDIO_I2S_METHOD_SIMPLEX

#ifdef AUDIO_I2S_METHOD_SIMPLEX

#define AUDIO_I2S_MIC_GPIO_WS   GPIO_NUM_4
#define AUDIO_I2S_MIC_GPIO_SCK  GPIO_NUM_5
#define AUDIO_I2S_MIC_GPIO_DIN  GPIO_NUM_6

#define AUDIO_I2S_SPK_GPIO_DOUT GPIO_NUM_7
#define AUDIO_I2S_SPK_GPIO_BCLK GPIO_NUM_15
#define AUDIO_I2S_SPK_GPIO_LRCK GPIO_NUM_16

#else

#define AUDIO_I2S_GPIO_WS GPIO_NUM_4
#define AUDIO_I2S_GPIO_BCLK GPIO_NUM_5
#define AUDIO_I2S_GPIO_DIN  GPIO_NUM_6
#define AUDIO_I2S_GPIO_DOUT GPIO_NUM_7

#endif


#define BUILTIN_LED_GPIO        GPIO_NUM_48
#define BOOT_BUTTON_GPIO        GPIO_NUM_0
#define TOUCH_BUTTON_GPIO       GPIO_NUM_47
#define VOLUME_UP_BUTTON_GPIO   GPIO_NUM_40
#define VOLUME_DOWN_BUTTON_GPIO GPIO_NUM_39

#define DISPLAY_SDA_PIN GPIO_NUM_41
#define DISPLAY_SCL_PIN GPIO_NUM_42
#define DISPLAY_WIDTH   128

#if CONFIG_OLED_SSD1306_128X32
#define DISPLAY_HEIGHT  32
#elif CONFIG_OLED_SSD1306_128X64
#define DISPLAY_HEIGHT  64
#else
#error "未选择 OLED 屏幕类型"
#endif

#define DISPLAY_MIRROR_X true
#define DISPLAY_MIRROR_Y true

// 定义 4 个舵机的 GPIO 引脚
#define SERVO1_PIN GPIO_NUM_13      //左前
#define SERVO2_PIN GPIO_NUM_14      //右前
#define SERVO3_PIN GPIO_NUM_17      //左后
#define SERVO4_PIN GPIO_NUM_18      //右后

// 定义 LEDC 通道和定时器
#define LEDC_TIMER LEDC_TIMER_3
#define LEDC_SPEED_MODE LEDC_LOW_SPEED_MODE
#define LEDC_FREQUENCY 50 // 舵机 PWM 频率 (50Hz)
#define LEDC_RESOLUTION LEDC_TIMER_13_BIT // PWM 分辨率 (13 位)

// 定义 LEDC CHANNEL
#define LEDC_CHANNEL1 LEDC_CHANNEL_1
#define LEDC_CHANNEL2 LEDC_CHANNEL_2
#define LEDC_CHANNEL3 LEDC_CHANNEL_3
#define LEDC_CHANNEL4 LEDC_CHANNEL_4


#endif // _BOARD_CONFIG_H_
